name: breakpoint_scaffold
description: A scaffold that responds to different screen sizes by moving the drawer, navigation bar, and side sheet. 
version: 0.0.2
repository: https://github.com/Levi-Lesches/Responsive-Scaffold

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  adaptive_breakpoints: ^0.0.4
  flutter:
    sdk: flutter
